---
title: "MICE"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
UKBB <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/charge_prevent_UKBB.csv")
```

```{r}
library(mice)

set.seed(123)
id <- UKBB$eid_visit

dat <- UKBB
dat$eid_visit <- NULL

imp <- mice(
  dat,
  m = 4,
  maxit = 20,
  seed = 123,
  printFlag = TRUE
)

UKBB_imp_list <- lapply(1:4, function(i) {
  out <- complete(imp, action = i)
  out$eid_visit <- id
  out <- out[, c("eid_visit", setdiff(colnames(out), "eid_visit"))]
  out
})

UKBB_imp1 <- UKBB_imp_list[[1]]
UKBB_imp2 <- UKBB_imp_list[[2]]
UKBB_imp3 <- UKBB_imp_list[[3]]
UKBB_imp4 <- UKBB_imp_list[[4]]
```
```{r}
library(dplyr)
library(pROC)

UKBB_charge1 <- UKBB_imp1 %>%
  mutate(charge_age    = agecmr/5*0.508,
         charge_race   = ifelse(ethnicity == 1, 0.465, 0),
         charge_height = ht/10*0.248,
         charge_weight = wt/15*0.115,
         charge_sbp    = sbp/20*0.197,
         charge_dbp    = dbp/10*(-0.101),
         charge_smk    = ifelse(cursmoke == 1, 0.359, 0),
         charge_htnmed = ifelse(htnmed == 1, 0.349, 0),
         charge_prevdm = ifelse(dm == 1, 0.237, 0),
         charge_prevhf = ifelse(prevhf == 1, 0.701, 0),
         charge_prevmi = ifelse(hxmi == 1, 0.496, 0),
         charge_sum    = charge_age + charge_race + charge_height + charge_weight + charge_sbp + charge_dbp +
                         charge_smk + charge_htnmed + charge_prevdm + charge_prevhf + charge_prevmi,
         charge_score  = 1 - 0.9718412736^(charge_sum - 12.5815600)) %>%
  select(eid_visit, charge_score)

UKBB_charge2 <- UKBB_imp2 %>%
  mutate(charge_age    = agecmr/5*0.508,
         charge_race   = ifelse(ethnicity == 1, 0.465, 0),
         charge_height = ht/10*0.248,
         charge_weight = wt/15*0.115,
         charge_sbp    = sbp/20*0.197,
         charge_dbp    = dbp/10*(-0.101),
         charge_smk    = ifelse(cursmoke == 1, 0.359, 0),
         charge_htnmed = ifelse(htnmed == 1, 0.349, 0),
         charge_prevdm = ifelse(dm == 1, 0.237, 0),
         charge_prevhf = ifelse(prevhf == 1, 0.701, 0),
         charge_prevmi = ifelse(hxmi == 1, 0.496, 0),
         charge_sum    = charge_age + charge_race + charge_height + charge_weight + charge_sbp + charge_dbp +
                         charge_smk + charge_htnmed + charge_prevdm + charge_prevhf + charge_prevmi,
         charge_score  = 1 - 0.9718412736^(charge_sum - 12.5815600)) %>%
  select(eid_visit, charge_score)

UKBB_charge3 <- UKBB_imp3 %>%
  mutate(charge_age    = agecmr/5*0.508,
         charge_race   = ifelse(ethnicity == 1, 0.465, 0),
         charge_height = ht/10*0.248,
         charge_weight = wt/15*0.115,
         charge_sbp    = sbp/20*0.197,
         charge_dbp    = dbp/10*(-0.101),
         charge_smk    = ifelse(cursmoke == 1, 0.359, 0),
         charge_htnmed = ifelse(htnmed == 1, 0.349, 0),
         charge_prevdm = ifelse(dm == 1, 0.237, 0),
         charge_prevhf = ifelse(prevhf == 1, 0.701, 0),
         charge_prevmi = ifelse(hxmi == 1, 0.496, 0),
         charge_sum    = charge_age + charge_race + charge_height + charge_weight + charge_sbp + charge_dbp +
                         charge_smk + charge_htnmed + charge_prevdm + charge_prevhf + charge_prevmi,
         charge_score  = 1 - 0.9718412736^(charge_sum - 12.5815600)) %>%
  select(eid_visit, charge_score)

UKBB_charge4 <- UKBB_imp4 %>%
  mutate(charge_age    = agecmr/5*0.508,
         charge_race   = ifelse(ethnicity == 1, 0.465, 0),
         charge_height = ht/10*0.248,
         charge_weight = wt/15*0.115,
         charge_sbp    = sbp/20*0.197,
         charge_dbp    = dbp/10*(-0.101),
         charge_smk    = ifelse(cursmoke == 1, 0.359, 0),
         charge_htnmed = ifelse(htnmed == 1, 0.349, 0),
         charge_prevdm = ifelse(dm == 1, 0.237, 0),
         charge_prevhf = ifelse(prevhf == 1, 0.701, 0),
         charge_prevmi = ifelse(hxmi == 1, 0.496, 0),
         charge_sum    = charge_age + charge_race + charge_height + charge_weight + charge_sbp + charge_dbp +
                         charge_smk + charge_htnmed + charge_prevdm + charge_prevhf + charge_prevmi,
         charge_score  = 1 - 0.9718412736^(charge_sum - 12.5815600)) %>%
  select(eid_visit, charge_score)
```

# CARDIAC-FM + CHARGE-AF


```{r}
test1 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGstage1_UKBB_split1.csv")
test2 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGstage1_UKBB_split2.csv")
test3 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGstage1_UKBB_split3.csv")
test4 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGstage1_UKBB_split4.csv")
```


```{r}
test1 <- test1 %>%
  left_join(
    UKBB_charge1 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test2 <- test2%>%
  left_join(
    UKBB_charge2 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test3 <- test3 %>%
  left_join(
    UKBB_charge3 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test4 <- test4 %>%
  left_join(
    UKBB_charge4 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )
```

```{r}
ecgmri <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_HR/ecgmri.csv")
test1 <- test1 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test2 <- test2 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test3 <- test3 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test4 <- test4 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
```


```{r}
UKBB_train <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/UKBB_train.csv")
colnames(UKBB_train)[1] <- "eid_visit"
UKBB_train$eid_visit <- sub("\\.mat$", "", UKBB_train$eid_visit)

UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge1 %>% 
      select(eid_visit, charge_pred1 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge2 %>% 
      select(eid_visit, charge_pred2 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge3 %>% 
      select(eid_visit, charge_pred3 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge4 %>% 
      select(eid_visit, charge_pred4 = charge_score),
    by = "eid_visit"
  )
```



```{r}
UKBB_train1 <- UKBB_train %>%
  select(af, af1_pred, charge_pred1) %>%
  na.omit()

UKBB_train2 <- UKBB_train %>%
  select(af, af2_pred, charge_pred2) %>%
  na.omit()

UKBB_train3 <- UKBB_train %>%
  select(af, af3_pred, charge_pred3) %>%
  na.omit()

UKBB_train4 <- UKBB_train %>%
  select(af, af4_pred, charge_pred4) %>%
  na.omit()

```

```{r}
test1
```

```{r}
library(dplyr)
library(pROC)

results <- list()

for (v in 1:4) {

  df_eval <- get(paste0("test", v)) %>%
    dplyr::select(eid_visit, af5, af5_pred, charge_score) %>%
    dplyr::rename(
      af = af5,
      !!paste0("af", v, "_pred") := af5_pred,
      !!paste0("charge_pred", v) := charge_score
    ) %>%
    na.omit()

  fit <- glm(
    as.formula(paste0("af ~ af", v, "_pred + charge_pred", v)),
    data = get(paste0("UKBB_train", v)),
    family = binomial(link = "logit")
  )

  df_eval$model_pred <- predict(fit, newdata = df_eval, type = "response")

  out_dir <- paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/",
    "split", v, "/UKBB/CHARGE_PREVENT"
  )
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

  df_out1 <- df_eval %>%
    dplyr::select(af, !!paste0("af", v, "_pred")) %>%
    dplyr::rename(
      y_true = af,
      y_pred = !!paste0("af", v, "_pred")
    )

  write.csv(df_out1, file.path(out_dir, "test_af5.csv"), row.names = FALSE)

  df_out2 <- df_eval %>%
    dplyr::select(af, model_pred) %>%
    dplyr::rename(
      y_true = af,
      y_pred = model_pred
    )

  write.csv(df_out2, file.path(out_dir, "test_af5_cardiacfm.csv"), row.names = FALSE)
  
  out_dir2 <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease"
  write.csv(df_eval, file.path(out_dir2, paste0("cardiacfm_charge_split", v,".csv")), row.names = FALSE)

  results[[v]] <- data.frame(
    version = v,
    auc_model = as.numeric(pROC::auc(df_eval$af, df_eval$model_pred)),
    auc_af = as.numeric(pROC::auc(df_eval$af, df_eval[[paste0("af", v, "_pred")]])),
    auc_charge = as.numeric(pROC::auc(df_eval$af, df_eval[[paste0("charge_pred", v)]]))
  )
}

auc_summary <- dplyr::bind_rows(results)
auc_summary

```


```{r}
data.frame(
  Model = c(
    "CARDIAC-FM + CHARGE-AF",
    "CARDIAC-FM",
    "CHARGE-AF"
  ),
  AUC = colMeans(auc_summary[, c("auc_model", "auc_af", "auc_charge")])
)
```

#### ECG-FM + CHARGE-AF


```{r}
test1 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGFM_UKBB_split1.csv")
test2 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGFM_UKBB_split2.csv")
test3 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGFM_UKBB_split3.csv")
test4 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGFM_UKBB_split4.csv")
```

```{r}
test1 <- test1 %>%
  left_join(
    UKBB_charge1 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test2 <- test2%>%
  left_join(
    UKBB_charge2 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test3 <- test3 %>%
  left_join(
    UKBB_charge3 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test4 <- test4 %>%
  left_join(
    UKBB_charge4 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )
```

```{r}
ecgmri <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_HR/ecgmri.csv")
test1 <- test1 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test2 <- test2 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test3 <- test3 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test4 <- test4 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
```


```{r}
UKBB_train <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/UKBB_train_ecgfm.csv")
colnames(UKBB_train)[1] <- "eid_visit"
UKBB_train$eid_visit <- sub("\\.mat$", "", UKBB_train$eid_visit)

UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge1 %>% 
      select(eid_visit, charge_pred1 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge2 %>% 
      select(eid_visit, charge_pred2 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge3 %>% 
      select(eid_visit, charge_pred3 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge4 %>% 
      select(eid_visit, charge_pred4 = charge_score),
    by = "eid_visit"
  )
```



```{r}
UKBB_train1 <- UKBB_train %>%
  select(af, af1_pred, charge_pred1) %>%
  na.omit()

UKBB_train2 <- UKBB_train %>%
  select(af, af2_pred, charge_pred2) %>%
  na.omit()

UKBB_train3 <- UKBB_train %>%
  select(af, af3_pred, charge_pred3) %>%
  na.omit()

UKBB_train4 <- UKBB_train %>%
  select(af, af4_pred, charge_pred4) %>%
  na.omit()

```

```{r}
library(dplyr)
library(pROC)

results <- list()

for (v in 1:4) {

  df_eval <- get(paste0("test", v)) %>%
    dplyr::select(eid_visit, af5, af5_pred, charge_score) %>%
    dplyr::rename(
      af = af5,
      !!paste0("af", v, "_pred") := af5_pred,
      !!paste0("charge_pred", v) := charge_score
    ) %>%
    na.omit()

  fit <- glm(
    as.formula(paste0("af ~ af", v, "_pred + charge_pred", v)),
    data = get(paste0("UKBB_train", v)),
    family = binomial(link = "logit")
  )

  df_eval$model_pred <- predict(fit, newdata = df_eval, type = "response")

  out_dir <- paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/",
    "split", v, "/UKBB/CHARGE_PREVENT"
  )
 
  df_out2 <- df_eval %>%
    dplyr::select(af, model_pred) %>%
    dplyr::rename(
      y_true = af,
      y_pred = model_pred
    )

  write.csv(df_out2, file.path(out_dir, "test_af5_ecgfm.csv"), row.names = FALSE)
  
  out_dir2 <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease"
  write.csv(df_eval, file.path(out_dir2, paste0("ecgfm_charge_split", v,".csv")), row.names = FALSE)

  results[[v]] <- data.frame(
    version = v,
    auc_model = as.numeric(pROC::auc(df_eval$af, df_eval$model_pred)),
    auc_af = as.numeric(pROC::auc(df_eval$af, df_eval[[paste0("af", v, "_pred")]])),
    auc_charge = as.numeric(pROC::auc(df_eval$af, df_eval[[paste0("charge_pred", v)]]))
  )
}

auc_summary <- dplyr::bind_rows(results)
auc_summary

```

```{r}
data.frame(
  Model = c(
    "ECG-FM + CHARGE-AF",
    "ECG-FM",
    "CHARGE-AF"
  ),
  AUC = colMeans(auc_summary[, c("auc_model", "auc_af", "auc_charge")])
)
```




#### CARDIAC-FM(ECG+MRI) + CHARGE-AF


```{r}
test1 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGMRIstage1_RF_UKBB_split1.csv")
test2 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGMRIstage1_RF_UKBB_split2.csv")
test3 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGMRIstage1_RF_UKBB_split3.csv")
test4 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGMRIstage1_RF_UKBB_split4.csv")
```

```{r}
test1 <- test1 %>%
  left_join(
    UKBB_charge1 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test2 <- test2%>%
  left_join(
    UKBB_charge2 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test3 <- test3 %>%
  left_join(
    UKBB_charge3 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )

test4 <- test4 %>%
  left_join(
    UKBB_charge4 %>% 
      select(eid_visit, charge_score),
    by = "eid_visit"
  )
```

```{r}
ecgmri <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_HR/ecgmri.csv")
test1 <- test1 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test2 <- test2 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test3 <- test3 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test4 <- test4 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
```


```{r}
UKBB_train <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/UKBB_train_ecgmri.csv")
colnames(UKBB_train)[1] <- "eid_visit"
UKBB_train$eid_visit <- sub("\\.mat$", "", UKBB_train$eid_visit)

UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge1 %>% 
      select(eid_visit, charge_pred1 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge2 %>% 
      select(eid_visit, charge_pred2 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge3 %>% 
      select(eid_visit, charge_pred3 = charge_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_charge4 %>% 
      select(eid_visit, charge_pred4 = charge_score),
    by = "eid_visit"
  )
```



```{r}
UKBB_train1 <- UKBB_train %>%
  select(af, af1_pred, charge_pred1) %>%
  na.omit()

UKBB_train2 <- UKBB_train %>%
  select(af, af2_pred, charge_pred2) %>%
  na.omit()

UKBB_train3 <- UKBB_train %>%
  select(af, af3_pred, charge_pred3) %>%
  na.omit()

UKBB_train4 <- UKBB_train %>%
  select(af, af4_pred, charge_pred4) %>%
  na.omit()

```

```{r}
library(dplyr)
library(pROC)

results <- list()

for (v in 1:4) {

  df_eval <- get(paste0("test", v)) %>%
    dplyr::select(eid_visit, af5, af5_pred, charge_score) %>%
    dplyr::rename(
      af = af5,
      !!paste0("af", v, "_pred") := af5_pred,
      !!paste0("charge_pred", v) := charge_score
    ) %>%
    na.omit()

  fit <- glm(
    as.formula(paste0("af ~ af", v, "_pred + charge_pred", v)),
    data = get(paste0("UKBB_train", v)),
    family = binomial(link = "logit")
  )

  df_eval$model_pred <- predict(fit, newdata = df_eval, type = "response")

  out_dir <- paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/",
    "split", v, "/UKBB/CHARGE_PREVENT"
  )
 
  df_out2 <- df_eval %>%
    dplyr::select(af, model_pred) %>%
    dplyr::rename(
      y_true = af,
      y_pred = model_pred
    )

  write.csv(df_out2, file.path(out_dir, "test_af5_cardiacfm_ecgmri.csv"), row.names = FALSE)
  
  out_dir2 <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease"
  write.csv(df_eval, file.path(out_dir2, paste0("cardiacfm_ecgmri_charge_split", v,".csv")), row.names = FALSE)


  results[[v]] <- data.frame(
    version = v,
    auc_model = as.numeric(pROC::auc(df_eval$af, df_eval$model_pred)),
    auc_af = as.numeric(pROC::auc(df_eval$af, df_eval[[paste0("af", v, "_pred")]])),
    auc_charge = as.numeric(pROC::auc(df_eval$af, df_eval[[paste0("charge_pred", v)]]))
  )
}

auc_summary <- dplyr::bind_rows(results)
auc_summary

```

```{r}
data.frame(
  Model = c(
    "CARDIAC-FM(ECG+MRI) + CHARGE-AF",
    "CARDIAC-FM(ECG+MRI)",
    "CHARGE-AF"
  ),
  AUC = colMeans(auc_summary[, c("auc_model", "auc_af", "auc_charge")])
)
```

