---
title: "CHS_subgroup"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pROC)
library(dplyr)
library(PRROC)
library(ggplot2)


CHS_info <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/CHS_rf.csv")
CHS_template <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/CHS_split1.csv")
CHS_info <- CHS_info[, c(1, 2, ncol(CHS_info))]
```


```{r}
cols_drop <- c(
  "af3_0","af3_10","af3_20",
  "af5_0","af5_10","af5_20",
  "hf3_0","hf3_10","hf3_20",
  "hf5_0","hf5_10","hf5_20"
)

CHS_template <- CHS_template[, !colnames(CHS_template) %in% cols_drop]

colnames(CHS_template) <- gsub("_ECGstage1_RF_", "_", colnames(CHS_template))

CHS_template <- CHS_template %>%
  dplyr::select(
    -matches("^(af|hf)3_")  
  ) %>%
  dplyr::rename_with(
    ~ str_replace(.x, "^(af|hf)5_", "\\1_"),  
    matches("^(af|hf)5_")
  )
```

```{r}
labels <- c("af", "hf")
suffixes <- c("0", "10", "20")

read_split <- function(split_num) {
  base <- paste0("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/split",
                 split_num, "/CHS/CHARGE")
  out <- list()
  for (lb in labels) {
    if (lb == "af"){
      base <- paste0("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/split",
                 split_num, "/CHS/CHARGE")
    }
    else {
      base <- paste0("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/split",
                 split_num, "/CHS/PREVENT")
    }
    for (suf in suffixes) {
      if (lb == "af"){
        fname <- paste0("test_", lb, "_charge_cardiacfm", suf, ".csv")
      }
      else{
        fname <- paste0("test_", lb, "_prevent_cardiacfm", suf, ".csv")
      }
      key <- paste0(lb, "_", suf)
      fpath <- file.path(base, fname)
      if (file.exists(fpath)) {
        out[[key]] <- read.csv(fpath)
      }
    }
  }
  out
}

tables_split1 <- read_split(1)
tables_split2 <- read_split(2)
tables_split3 <- read_split(3)
tables_split4 <- read_split(4)

```



```{r}
fill_CHS <- function(template, tables_split) {
  out <- template
  
  for (nm in names(tables_split)) {
    mask <- !is.na(template[[nm]])
    vals <- tables_split[[nm]]$y_pred
    out[[nm]][mask] <- vals
  }
  
  out
}

CHS1 <- fill_CHS(CHS_template, tables_split1)
CHS2 <- fill_CHS(CHS_template, tables_split2)
CHS3 <- fill_CHS(CHS_template, tables_split3)
CHS4 <- fill_CHS(CHS_template, tables_split4)
```

```{r}
af_true <- rep(NA, nrow(CHS1))
non_na_positions <- which(!is.na(CHS1$af_0))
af_true[non_na_positions] <- tables_split4$af_0$y_true
CHS1$af_true <- af_true

hf_true <- rep(NA, nrow(CHS1))
non_na_positions <- which(!is.na(CHS1$hf_0))
hf_true[non_na_positions] <- tables_split4$hf_0$y_true
CHS1$hf_true <- hf_true

CHS2[, c("af_true", "hf_true")] <- CHS1[, c("af_true", "hf_true")]
CHS3[, c("af_true", "hf_true")] <- CHS1[, c("af_true", "hf_true")]
CHS4[, c("af_true", "hf_true")] <- CHS1[, c("af_true", "hf_true")]
```


```{r}
CHS1 <- merge(CHS1, CHS_info, by = "id", all.x = TRUE)
CHS2 <- merge(CHS2, CHS_info, by = "id", all.x = TRUE)
CHS3 <- merge(CHS3, CHS_info, by = "id", all.x = TRUE)
CHS4 <- merge(CHS4, CHS_info, by = "id", all.x = TRUE)
```


```{r}
keep_cols <- c(1:7, (ncol(CHS1)-5):ncol(CHS1))
CHS1 <- CHS1 %>% select(all_of(keep_cols))
CHS2 <- CHS2 %>% select(all_of(keep_cols))
CHS3 <- CHS3 %>% select(all_of(keep_cols))
CHS4 <- CHS4 %>% select(all_of(keep_cols))
```

```{r}
add_suffix <- function(df, suffix) {
  col_indices <- 2:7
  new_names <- paste0(names(df)[col_indices], suffix)
  names(df)[col_indices] <- new_names
  return(df)
}

CHS1 <- add_suffix(CHS1, "_pred1")
CHS2 <- add_suffix(CHS2, "_pred2")
CHS3 <- add_suffix(CHS3, "_pred3")
CHS4 <- add_suffix(CHS4, "_pred4")
```


```{r}
CHS_merged <- CHS1
for(i in 2:4) {
  df_name <- paste0("CHS", i)
  temp_df <- get(df_name)[, 1:7]
  CHS_merged <- merge(CHS_merged, temp_df, by = "id", all = TRUE)
}
```


```{r}
labels <- c("af", "hf")
ratios <- c("0", "10", "20")
sps <- 1:4

summary_results <- data.frame()

for (label in labels) {
  true_col <- paste0(label, "_true")
  
  for (ratio in ratios) {
    pred_cols <- paste0(label, "_", ratio, "_pred", sps)
    
    subgroups_list <- list(
      overall = rep(TRUE, nrow(CHS_merged)),
      age_lt_75 = CHS_merged$age < 75,
      age_gt_75 = CHS_merged$age >= 75,
      gender_0 = CHS_merged$gender == 0,
      gender_1 = CHS_merged$gender == 1
    )
    
    for (subgroup_name in names(subgroups_list)) {
      subgroup_mask <- subgroups_list[[subgroup_name]]
      
      auc_results <- numeric(length(sps))
      auprc_results <- numeric(length(sps))
      
      for (i in 1:length(sps)) {
        df_temp <- CHS_merged[subgroup_mask, c(true_col, pred_cols[i])]
        df_temp <- df_temp[complete.cases(df_temp), ]
        
        if (nrow(df_temp) == 0) {
          auc_results[i] <- NA
          auprc_results[i] <- NA
          next
        }
        
        roc_obj <- roc(df_temp[[1]], df_temp[[2]])
        auc_results[i] <- auc(roc_obj)
        
        pr_curve <- pr.curve(scores.class0 = df_temp[[2]][df_temp[[1]] == 1],
                            scores.class1 = df_temp[[2]][df_temp[[1]] == 0])
        auprc_results[i] <- pr_curve$auc.integral
      }
      
      auc_sd <- sd(auc_results, na.rm = TRUE)
      auprc_sd <- sd(auprc_results, na.rm = TRUE)
      
      summary_results <- rbind(summary_results, 
                              data.frame(
                                model = "ECGstage1_downstream",
                                label = label,
                                subgroup = subgroup_name,
                                ratio = ratio,
                                AUROC_sd = auc_sd,
                                AUPRC_sd = auprc_sd,
                                AUROC = mean(auc_results, na.rm = TRUE),
                                AUPRC = mean(auprc_results, na.rm = TRUE)
                              ))
    }
  }
}

summary_results <- summary_results %>%
  mutate(
    AUROC_lower = AUROC - 1.96 * AUROC_sd / sqrt(4),
    AUROC_upper = AUROC + 1.96 * AUROC_sd / sqrt(4),
    AUPRC_lower = AUPRC - 1.96 * AUPRC_sd / sqrt(4),
    AUPRC_upper = AUPRC + 1.96 * AUPRC_sd / sqrt(4)
  )

print(summary_results)
```


```{r}
summary_results$model <- case_when(
  summary_results$model == "ECGstage1_downstream" ~ "CARDIAC-FM(ECG+CHARGE-AF)",
  TRUE ~ summary_results$model
)

summary_results$label <- case_when(
  summary_results$label == "af" ~ "Atrial Fibrillation",
  summary_results$label == "hf" ~ "Heart Failure",
  TRUE ~ summary_results$label
)
```


```{r}
summary_results$ratio <- factor(ifelse(summary_results$ratio == 0, "Zero-shot",
                                 ifelse(summary_results$ratio == 10, "Few-shot(10%)",
                                 ifelse(summary_results$ratio == 20, "Few-shot(20%)", 
                                 summary_results$ratio))),
                                 levels = c("Zero-shot", "Few-shot(10%)", "Few-shot(20%)"))
```

```{r}
df_plot_af <- summary_results %>%
  filter(label == "Atrial Fibrillation") %>%
    mutate(
      subgroup = recode(subgroup,
                        "age_lt_75" = "Age <75",
                        "age_gt_75" = "Age ≥75",
                        "gender_0" = "Female",
                        "gender_1" = "Male",
                        "overall" = "Overall"),
      group_type = case_when(
        grepl("Age", subgroup) ~ "Age",
        grepl("Female|Male", subgroup) ~ "Sex",
        subgroup == "Overall" ~ "Overall"
      )
    )

df_plot_hf <- summary_results %>%
  filter(label == "Heart Failure") %>%
    mutate(
      subgroup = recode(subgroup,
                        "age_lt_75" = "Age <75",
                        "age_gt_75" = "Age ≥75",
                        "gender_0" = "Female",
                        "gender_1" = "Male",
                        "overall" = "Overall"),
      group_type = case_when(
        grepl("Age", subgroup) ~ "Age",
        grepl("Female|Male", subgroup) ~ "Sex",
        subgroup == "Overall" ~ "Overall"
      )
    )
```


```{r}
df_all <- dplyr::bind_rows(df_plot_af, df_plot_hf)
```
```{r}
df_plot <- df_all %>%
  mutate(
    subgroup = factor(subgroup, levels = c("Overall", "Male", "Female", "Age ≥75", "Age <75")),
    ratio = factor(ratio, levels = c("Zero-shot", "Few-shot(10%)", "Few-shot(20%)"))
  )

ggplot(df_plot, aes(x = AUROC, y = subgroup, color = ratio, shape = ratio)) +
  geom_errorbarh(
    aes(xmin = AUROC_lower, xmax = AUROC_upper),
    position = position_dodge(width = 0.6),
    height = 0.2,
    linewidth = 0.5
  ) +
  geom_point(position = position_dodge(width = 0.6), size = 2) +
  facet_wrap(~label, nrow = 1) +
  scale_shape_manual(values = c(15, 16, 17)) +
  scale_color_manual(values = c("#D55E00", "#009E73", "#0072B2")) +
  coord_cartesian(xlim = c(0.55, 0.95)) +
  labs(x = "AUROC", y = "Subgroup", color = NULL, shape = NULL) +
  theme_bw(base_size = 16) +
  theme(
    axis.title.x = element_text(size = 15, face = "bold"),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x  = element_text(size = 12, face = "bold"),
    axis.text.y  = element_text(size = 12, face = "bold"),
    strip.text   = element_text(size = 15, face = "bold"),
    legend.text  = element_text(size = 15, face = "bold"),
    legend.position = "bottom",
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank()
  )

```


```{r}
write.csv(df_plot_af, "/Users/fuminli/Desktop/ECG_MRI/result_table/CHS_subgroup_af5.csv", row.names = FALSE)
write.csv(df_plot_hf, "/Users/fuminli/Desktop/ECG_MRI/result_table/CHS_subgroup_hf5.csv", row.names = FALSE)
```

