---
title: "surv"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(survminer)  
library(ggplot2)
```

```{r}
af2 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/af2.csv")
af3 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/af3.csv")
hf2 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/hf2.csv")
hf3 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/hf3.csv")

af2 <- na.omit(af2)
af3 <- na.omit(af3)
hf2 <- na.omit(hf2)
hf3 <- na.omit(hf3)
```

```{r}
intersection_list <- readLines("/Users/fuminli/Desktop/ECG_MRI/intersection_list.csv")
intersection_list2 <- sub("_2$", "", intersection_list[grepl("_2$", intersection_list)])
intersection_list3 <- sub("_3$", "", intersection_list[grepl("_3$", intersection_list)])

af2 <- af2[af2$eid %in% intersection_list2, ]
hf2 <- hf2[hf2$eid %in% intersection_list2, ]

af3 <- af3[af3$eid %in% intersection_list3, ]
hf3 <- hf3[hf3$eid %in% intersection_list3, ]
```

```{r}
names(af2)[names(af2) == "afcens"] <- "disease"
names(af2)[names(af2) == "ttoaf"] <- "days"
af2 = af2[, c("disease", "days")]
```

```{r}
names(af3)[names(af3) == "afcens"] <- "disease"
names(af3)[names(af3) == "ttoaf2"] <- "days"
af3 = af3[, c("disease", "days")]
af3 = af3[af3$days >= 0, ]
```

```{r}
af2$group <- "Group 1"
af3$group <- "Group 2"

af_all <- rbind(af2, af3)
af_all$years <- af_all$days / 365

fit <- survfit(Surv(years, disease) ~ group, data = af_all)

af <- ggsurvplot(
  fit, data = af_all,
  conf.int = TRUE,
  pval = TRUE,
  risk.table = TRUE,                
  risk.table.y.text.col = TRUE,     
  risk.table.col = "strata",      
  risk.table.height = 0.25,
  risk.table.fontsize = 5,
  risk.table.fontface = "bold",
  surv.scale = "percent",
  xlab = "Years", ylab = "Event-free survival(%)",
  title = "Atrial fibrillation",
  legend.labs = c("Baseline", "Follow-up"),
  legend.title = NULL,
  xlim = c(0, max(af_all$years)), ylim = c(0.94, 1),
  break.time.by = 1, censor = FALSE, size = 1.2,
  palette = c("red", "blue"),
  ggtheme = theme_bw(base_size = 18),
  tables.title = "No. at risk" 
)

af$plot <- af$plot + theme(
  axis.title = element_text(size = 20, face = "bold"),
  axis.text  = element_text(size = 16, face = "bold"),
  legend.text = element_text(size = 16, face = "bold"),
  plot.title  = element_text(size = 20, face = "bold", hjust = 0.5),
  legend.position = c(0.98, 0.98),
  legend.justification = c(1, 1),
  legend.background = element_rect(fill = alpha("white", 0.6))
)

af$table <- af$table + theme(
  axis.text = element_text(size = 12, face = "bold"),
  axis.title.x = element_text(size = 14, face = "bold")
)

print(af)
```

```{r}
names(hf2)[names(hf2) == "hfcens"] <- "disease"
names(hf2)[names(hf2) == "ttohf"] <- "days"
hf2 = hf2[, c("disease", "days")]
```

```{r}
names(hf3)[names(hf3) == "hfcens"] <- "disease"
names(hf3)[names(hf3) == "ttohf2"] <- "days"
hf3 = hf3[, c("disease", "days")]
hf3 = hf3[hf3$days >= 0, ]
```

```{r}
hf2$group <- "Group 1"
hf3$group <- "Group 2"

hf_all <- rbind(hf2, hf3)
hf_all$years <- hf_all$days / 365.25

fit <- survfit(Surv(time = hf_all$years, event = hf_all$disease) ~ group, data = hf_all)

hf <- ggsurvplot(
  fit,
  data = hf_all,
  conf.int = TRUE,
  pval = TRUE,
  risk.table = TRUE,                
  risk.table.y.text.col = TRUE,      
  risk.table.col = "strata",        
  risk.table.height = 0.25,        
  risk.table.fontsize = 5,
  risk.table.fontface = "bold",
  surv.scale = "percent",
  xlab = "Years",
  ylab = "Event-free survival (%)",
  title = "Heart Failure",
  legend.labs = c("Baseline", "Follow-up"),
  legend.title = NULL,
  xlim = c(0, max(hf_all$years)),
  ylim = c(0.97, 1),
  break.time.by = 1,
  censor = FALSE,
  size = 1.2,
  palette = c("red", "blue"),
  ggtheme = theme_bw(base_size = 18),
  tables.title = "No. at risk" 
)

hf$plot <- hf$plot + theme(
  axis.title = element_text(size = 20, face = "bold"),
  axis.text = element_text(size = 16, face = "bold"),
  legend.text = element_text(size = 16, face = "bold"),
  plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
  legend.position = c(0.98, 0.98),
  legend.justification = c(1, 1),
  legend.background = element_rect(fill = alpha("white", 0.6))
)

hf$table <- hf$table + theme(
  axis.text = element_text(size = 12, face = "bold"),
  axis.title.x = element_text(size = 14, face = "bold")
)

print(hf)

```

```{r}
png("/Users/fuminli/Desktop/ECG_MRI/AF_KM.png", width = 3000, height = 3000, res = 300)
print(af)       
dev.off()
```

```{r}
png("/Users/fuminli/Desktop/ECG_MRI/HF_KM.png", width = 3000, height = 3000, res = 300)
print(hf)       
dev.off()
```

## Based on different startification

```{r}
ecg <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_HR/ecg.csv")
ecgmri <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_HR/ecgmri.csv")
ecg <- ecg %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
```


```{r}
path <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease"

ecgmrirf_splits <- lapply(1:4, function(i) {
  read.csv(file.path(path, paste0("charge_prevent_cardiacfm_ecgmri_UKBB_split", i, ".csv")))
})


ecgrf_splits <- lapply(1:4, function(i) {
  df <- read.csv(file.path(path, paste0("charge_prevent_cardiacfm_UKBB_split", i, ".csv")))
  df %>% filter(eid_visit %in% ecg$eid_visit)
})

rf_splits <- lapply(1:4, function(i) {
  df <- read.csv(file.path(path, paste0("charge_prevent_UKBB_split", i, ".csv")))
  df %>% filter(eid_visit %in% ecg$eid_visit)
})


```

```{r}
rf <- rf_splits[[1]]
rf$af5_pred <- rowMeans(
  cbind(
    rf_splits[[1]]$af5_pred,
    rf_splits[[2]]$af5_pred,
    rf_splits[[3]]$af5_pred,
    rf_splits[[4]]$af5_pred
  ),
)

rf$hf5_pred <- rowMeans(
  cbind(
    rf_splits[[1]]$hf5_pred,
    rf_splits[[2]]$hf5_pred,
    rf_splits[[3]]$hf5_pred,
    rf_splits[[4]]$hf5_pred
  ),
)

ecgrf <- ecgrf_splits[[1]]
ecgrf$af5_pred <- rowMeans(
  cbind(
    ecgrf_splits[[1]]$af5_pred,
    ecgrf_splits[[2]]$af5_pred,
    ecgrf_splits[[3]]$af5_pred,
    ecgrf_splits[[4]]$af5_pred
  ),
)
ecgrf$hf5_pred <- rowMeans(
  cbind(
    ecgrf_splits[[1]]$hf5_pred,
    ecgrf_splits[[2]]$hf5_pred,
    ecgrf_splits[[3]]$hf5_pred,
    ecgrf_splits[[4]]$hf5_pred
  ),
)
ecgmrirf <- ecgmrirf_splits[[1]]
ecgmrirf$af5_pred <- rowMeans(
  cbind(
    ecgmrirf_splits[[1]]$af5_pred,
    ecgmrirf_splits[[2]]$af5_pred,
    ecgmrirf_splits[[3]]$af5_pred,
    ecgmrirf_splits[[4]]$af5_pred
  ),
)
ecgmrirf$hf5_pred <- rowMeans(
  cbind(
    ecgmrirf_splits[[1]]$hf5_pred,
    ecgmrirf_splits[[2]]$hf5_pred,
    ecgmrirf_splits[[3]]$hf5_pred,
    ecgmrirf_splits[[4]]$hf5_pred
  ),
)
```

```{r}
model_cols <- c("af5_pred", "hf5_pred")
```

```{r}
add_qt <- function(df, cols) {
  out <- df
  for (nm in cols) {
    x <- df[[nm]]
    qs <- quantile(x, probs = c(1/3, 2/3), na.rm = TRUE)
    out[[paste0(nm, "_qt")]] <- dplyr::case_when(
      is.na(x) ~ NA_character_,
      x <= qs[1] ~ "low",
      x <= qs[2] ~ "intermediate",
      TRUE ~ "high"
    )
  }
  out
}
```

```{r}
model_cols <- c("af5_pred", "hf5_pred")

rf <- add_qt(rf, model_cols)
ecgrf <- add_qt(ecgrf, model_cols)
ecgmrirf <- add_qt(ecgmrirf, model_cols)
```

```{r}
ecg_outcome_df <- ecg[, c("eid_visit",
                      "prevaf","ttoaf","afcens",
                      "prevhf","ttohf","hfcens",
                      "previs","ttois","iscens")]
ecgmri_outcome_df <- ecgmri[, c("eid_visit",
                      "prevaf","ttoaf","afcens",
                      "prevhf","ttohf","hfcens",
                      "previs","ttois","iscens")]
rf_outcome <- merge(rf, ecg_outcome_df, by = "eid_visit", all = FALSE)
ecgrf_outcome <- merge(ecgrf, ecg_outcome_df, by = "eid_visit", all = FALSE)
ecgmrirf_outcome <- merge(ecgmrirf, ecgmri_outcome_df, by = "eid_visit", all = FALSE)
```


```{r}
af5 <- rf_outcome %>%
  select(group = af5_pred_qt, 
         days = ttoaf, 
         disease = afcens)

af5$years <- af5$days / 365.25
af5 <- na.omit(af5)
rownames(af5) <- NULL

hf5 <- rf_outcome %>%
  select(group = hf5_pred_qt, 
         days = ttohf, 
         disease = hfcens)

hf5$years <- hf5$days / 365.25
hf5 <- na.omit(hf5)
rownames(hf5) <- NULL
```


```{r}
fit <- survfit(Surv(years, disease) ~ group, data = af5)

af5_result <- ggsurvplot(
  fit, data = af5,
  conf.int = TRUE,
  pval = TRUE,
  risk.table = TRUE,                
  risk.table.y.text.col = TRUE,     
  risk.table.col = "strata",      
  risk.table.height = 0.25,
  risk.table.fontsize = 5,
  risk.table.fontface = "bold",
  surv.scale = "percent",
  xlab = "Years", ylab = "Event-free survival(%)",
  title = "Atrial fibrillation",
  legend.labs = c("Low", "Intermediate", "High"),
  legend.title = NULL,
  xlim = c(0, max(af5$years)), ylim = c(0.8, 1),
  break.time.by = 1, censor = FALSE, size = 1.2,
  palette = c("red", "blue", "purple"),
  ggtheme = theme_bw(base_size = 18),
  tables.title = "No. at risk" 
)

af5_result$plot <- af5_result$plot + theme(
  axis.title = element_text(size = 20, face = "bold"),
  axis.text  = element_text(size = 16, face = "bold"),
  legend.text = element_text(size = 16, face = "bold"),
  plot.title  = element_text(size = 20, face = "bold", hjust = 0.5),
  legend.position = c(0.4, 0.5),
  legend.justification = c(1, 1),
  legend.background = element_rect(fill = alpha("white", 0.6))
)

af5_result$table <- af5_result$table + theme(
  axis.text = element_text(size = 12, face = "bold"),
  axis.title.x = element_text(size = 14, face = "bold")
)

af5_result
```



```{r}
fit <- survfit(Surv(years, disease) ~ group, data = hf5)

hf5_result <- ggsurvplot(
  fit, data = hf5,
  conf.int = TRUE,
  pval = TRUE,
  risk.table = TRUE,                
  risk.table.y.text.col = TRUE,     
  risk.table.col = "strata",      
  risk.table.height = 0.25,
  risk.table.fontsize = 5,
  risk.table.fontface = "bold",
  surv.scale = "percent",
  xlab = "Years", ylab = "Event-free survival(%)",
  title = "Heart Failure",
  legend.labs = c("Low", "Intermediate", "High"),
  legend.title = NULL,
  xlim = c(0, max(hf5$years)), ylim = c(0.85, 1),
  break.time.by = 1, censor = FALSE, size = 1.2,
  palette = c("red", "blue", "purple"),
  ggtheme = theme_bw(base_size = 18),
  tables.title = "No. at risk" 
)

hf5_result$plot <- hf5_result$plot + theme(
  axis.title = element_text(size = 20, face = "bold"),
  axis.text  = element_text(size = 16, face = "bold"),
  legend.text = element_text(size = 16, face = "bold"),
  plot.title  = element_text(size = 20, face = "bold", hjust = 0.5),
  legend.position = c(0.4, 0.5),
  legend.justification = c(1, 1),
  legend.background = element_rect(fill = alpha("white", 0.6))
)

hf5_result$table <- hf5_result$table + theme(
  axis.text = element_text(size = 12, face = "bold"),
  axis.title.x = element_text(size = 14, face = "bold")
)

hf5_result
```



```{r}
png("/Users/fuminli/Desktop/ECG_MRI/AF5_KM.png", width = 3000, height = 3000, res = 300)
print(af5_result)       
dev.off()

png("/Users/fuminli/Desktop/ECG_MRI/HF5_KM.png", width = 3000, height = 3000, res = 300)
print(hf5_result)       
dev.off()
```


