---
title: "MESA_AUC_AUPRC"
author: "Fumin Li"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### MESA Zero-shot

```{r}
library(pROC)
library(PRROC)
library(dplyr)
library(ggplot2)
library(ggpattern)


base_dir <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp"
splits <- 1:4
labels <- c("af5", "hf5")
models <- c("RF", "ECGStage1+RF", "ECGStage1", "ECGFM", "ECGFM+RF")

results <- data.frame()

for (model in models) {
  for (label in labels) {
    for (split in splits) {
      suffix <- switch(model,
        "RF" = paste0("CHARGE_PREVENT/test_", label, ".csv"),
        "ECGFM" = paste0("ECGFM_downstream/test_", label, "_long_full_0.csv"),
        "ECGStage1" = paste0("ECGstage1_downstream/test_", label, "_long_full_0.csv"),
        "ECGStage1+RF" = paste0("CHARGE_PREVENT/test_", label, "_cardiacfm0.csv"),
        "ECGFM+RF" = paste0("CHARGE_PREVENT/test_", label, "_ecgfm0.csv"),
       )

      file_path <- file.path(base_dir, paste0("split", split), "MESA", suffix)
      print(file_path)

      if (file.exists(file_path)) {
        df <- read.csv(file_path)
        
        df <- read.csv(file_path)
        df$y_true <- as.numeric(gsub("\\[|\\]", "", df$y_true))
        df$y_pred <- as.numeric(gsub("\\[|\\]", "", df$y_pred))


        # AUC
        auc_val <- suppressWarnings(pROC::auc(df$y_true, df$y_pred, direction = "<"))

        # AUPRC
        pr <- PRROC::pr.curve(scores.class0 = df$y_pred[df$y_true == 1],
                              scores.class1 = df$y_pred[df$y_true == 0],
                              curve = FALSE)

        # positive ratio
        pos_ratio <- mean(df$y_true)

        # combine
        results <- rbind(
          results,
          data.frame(
            model = model,
            label = label,
            split = split,
            AUROC = auc_val,
            AUPRC = pr$auc.integral,
            pos_ratio = pos_ratio
          )
        )
      }
    }
  }
}

results <- results %>%
  arrange(model, label, split)

results0 <- results 

print(results)

```
```{r}
summary_auc <- results %>%
  group_by(label, model) %>%
  summarise(
    mean_auc = mean(AUROC, na.rm = TRUE),
    se_auc   = sd(AUROC, na.rm = TRUE) / sqrt(n()),
    lower    = mean_auc - 1.96 * se_auc,
    upper    = mean_auc + 1.96 * se_auc,
    .groups  = "drop"
  )
summary_auprc <- results %>%
  group_by(label, model) %>%
  summarise(
    mean_auprc = mean(AUPRC, na.rm = TRUE),
    se_auprc   = sd(AUPRC, na.rm = TRUE) / sqrt(n()),
    lower      = mean_auprc - 1.96 * se_auprc,
    upper      = mean_auprc + 1.96 * se_auprc,
    .groups    = "drop"
  )

summary_auc0 = summary_auc
summary_auprc0 = summary_auprc
```

```{r}
write.csv(summary_auc[,1:6], "/Users/fuminli/Desktop/ECG_MRI/result_table/MESA_AUC_0.csv")
write.csv(summary_auprc[,1:6], "/Users/fuminli/Desktop/ECG_MRI/result_table/MESA_AUPRC_0.csv")
```

#### MESA few-shot(10%)

```{r}
base_dir <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp"
splits <- 1:4
labels <- c("af5", "hf5")
models <- c("ECGStage1+RF", "ECGStage1", "ECGFM", "ECGFM+RF")

results <- data.frame()

for (model in models) {
  for (label in labels) {
    for (split in splits) {
      suffix <- switch(model,
        "ECGFM" = paste0("ECGFM_downstream/test_", label, "_long_full_10.csv"),
        "ECGStage1" = paste0("ECGstage1_downstream/test_", label, "_long_full_10.csv"),
        "ECGStage1+RF" = paste0("CHARGE_PREVENT/test_", label, "_cardiacfm10.csv"),
        "ECGFM+RF" = paste0("CHARGE_PREVENT/test_", label, "_ecgfm10.csv"),
       )

      file_path <- file.path(base_dir, paste0("split", split), "MESA", suffix)
      print(file_path)

      if (file.exists(file_path)) {
        df <- read.csv(file_path)
        
        df <- read.csv(file_path)
        df$y_true <- as.numeric(gsub("\\[|\\]", "", df$y_true))
        df$y_pred <- as.numeric(gsub("\\[|\\]", "", df$y_pred))


        # AUC
        auc_val <- suppressWarnings(pROC::auc(df$y_true, df$y_pred))

        # AUPRC
        pr <- PRROC::pr.curve(scores.class0 = df$y_pred[df$y_true == 1],
                              scores.class1 = df$y_pred[df$y_true == 0],
                              curve = FALSE)

        # positive ratio
        pos_ratio <- mean(df$y_true)

        # combine
        results <- rbind(
          results,
          data.frame(
            model = model,
            label = label,
            split = split,
            AUROC = auc_val,
            AUPRC = pr$auc.integral,
            pos_ratio = pos_ratio
          )
        )
      }
    }
  }
}

results <- results %>%
  arrange(model, label, split)

results10 <- results 

print(results)
```

```{r}
summary_auc <- results %>%
  group_by(label, model) %>%
  summarise(
    mean_auc = mean(AUROC, na.rm = TRUE),
    se_auc   = sd(AUROC, na.rm = TRUE) / sqrt(n()),
    lower    = mean_auc - 1.96 * se_auc,
    upper    = mean_auc + 1.96 * se_auc,
    .groups  = "drop"
  )
summary_auprc <- results %>%
  group_by(label, model) %>%
  summarise(
    mean_auprc = mean(AUPRC, na.rm = TRUE),
    se_auprc   = sd(AUPRC, na.rm = TRUE) / sqrt(n()),
    lower      = mean_auprc - 1.96 * se_auprc,
    upper      = mean_auprc + 1.96 * se_auprc,
    .groups    = "drop"
  )

summary_auc10 = summary_auc
summary_auprc10 = summary_auprc
```

```{r}
write.csv(summary_auc[,1:6], "/Users/fuminli/Desktop/ECG_MRI/result_table/MESA_AUC_10.csv")
write.csv(summary_auprc[,1:6], "/Users/fuminli/Desktop/ECG_MRI/result_table/MESA_AUPRC_10.csv")
```

#### MESA few-shot(20%)

```{r}
base_dir <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp"
splits <- 1:4
labels <- c("af5", "hf5")
models <- c("ECGStage1+RF", "ECGStage1", "ECGFM", "ECGFM+RF")

results <- data.frame()

for (model in models) {
  for (label in labels) {
    for (split in splits) {
      suffix <- switch(model,
        "ECGFM" = paste0("ECGFM_downstream/test_", label, "_long_full_20.csv"),
        "ECGStage1" = paste0("ECGstage1_downstream/test_", label, "_long_full_20.csv"),
        "ECGStage1+RF" = paste0("CHARGE_PREVENT/test_", label, "_cardiacfm20.csv"),
        "ECGFM+RF" = paste0("CHARGE_PREVENT/test_", label, "_ecgfm20.csv"),
       )

      file_path <- file.path(base_dir, paste0("split", split), "MESA", suffix)
      print(file_path)

      if (file.exists(file_path)) {
        df <- read.csv(file_path)
        
        df <- read.csv(file_path)
        df$y_true <- as.numeric(gsub("\\[|\\]", "", df$y_true))
        df$y_pred <- as.numeric(gsub("\\[|\\]", "", df$y_pred))


        # AUC
        auc_val <- suppressWarnings(pROC::auc(df$y_true, df$y_pred))

        # AUPRC
        pr <- PRROC::pr.curve(scores.class0 = df$y_pred[df$y_true == 1],
                              scores.class1 = df$y_pred[df$y_true == 0],
                              curve = FALSE)

        # positive ratio
        pos_ratio <- mean(df$y_true)

        # combine
        results <- rbind(
          results,
          data.frame(
            model = model,
            label = label,
            split = split,
            AUROC = auc_val,
            AUPRC = pr$auc.integral,
            pos_ratio = pos_ratio
          )
        )
      }
    }
  }
}

results <- results %>%
  arrange(model, label, split)

results20 <- results 

print(results)

```

```{r}
summary_auc <- results %>%
  group_by(label, model) %>%
  summarise(
    mean_auc = mean(AUROC, na.rm = TRUE),
    se_auc   = sd(AUROC, na.rm = TRUE) / sqrt(n()),
    lower    = mean_auc - 1.96 * se_auc,
    upper    = mean_auc + 1.96 * se_auc,
    .groups  = "drop"
  )

summary_auprc <- results %>%
  group_by(label, model) %>%
  summarise(
    mean_auprc = mean(AUPRC, na.rm = TRUE),
    se_auprc   = sd(AUPRC, na.rm = TRUE) / sqrt(n()),
    lower      = mean_auprc - 1.96 * se_auprc,
    upper      = mean_auprc + 1.96 * se_auprc,
    .groups    = "drop"
  )


summary_auc20 = summary_auc
summary_auprc20 = summary_auprc

```

```{r}
write.csv(summary_auc[,1:6], "/Users/fuminli/Desktop/ECG_MRI/result_table/MESA_AUC_20.csv")
write.csv(summary_auprc[,1:6], "/Users/fuminli/Desktop/ECG_MRI/result_table/MESA_AUPRC_20.csv")
```

```{r}
s0  <- summary_auc0  %>% mutate(shift = "Zero-shot")
s10 <- summary_auc10 %>% mutate(shift = "Few-shot(10%)")
s20 <- summary_auc20 %>% mutate(shift = "Few-shot(20%)")

df_af5 <- bind_rows(s0, s10, s20) %>%
  filter(label == "af5") %>%
  mutate(shift = factor(shift,
                        levels = c("Zero-shot", "Few-shot(10%)", "Few-shot(20%)")))

df_hf5 <- bind_rows(s0, s10, s20) %>%
  filter(label == "hf5") %>%
  mutate(shift = factor(shift,
                        levels = c("Zero-shot", "Few-shot(10%)", "Few-shot(20%)")))



```



# Pattern setting
```{r}
pattern_map <- c(
  "Risk Score"="none",
  "ECG-FM"="none",
  "CARDIAC-FM (ECG)"="none",
  "ECG-FM + Risk Score"="stripe",
  "CARDIAC-FM (ECG + Risk Score)"="stripe"
)

label_map <- c(
  "af3" = "3-year AF",
  "af5" = "5-year AF",
  "hf3" = "3-year HF",
  "hf5" = "5-year HF"
)

model_map <- c(
  "RF" = "Risk Score",
  "ECGFM" = "ECG-FM",
  "ECGStage1" = "CARDIAC-FM (ECG)",
  "ECGFM+RF"= "ECG-FM + Risk Score",
  "ECGStage1+RF"="CARDIAC-FM (ECG + Risk Score)"
)


order_models <- c(
  "Risk Score", "ECG-FM", "CARDIAC-FM (ECG)", "ECG-FM + Risk Score", "CARDIAC-FM (ECG + Risk Score)"
)

order_labels <- c(
  "3-year AF", "5-year AF", "3-year HF", "5-year HF"
)
```

```{r}
df_af5$label <- label_map[df_af5$label]
df_af5$model <- model_map[df_af5$model]

present_models = intersect(order_models, unique(df_af5$model))
df_af5$model <- factor(df_af5$model, levels = present_models)

pal <- c(
  "#8C564B",
  "#4C72B0",
  "#66C2A5",
  "#4C72B0",
  "#66C2A5"
)[seq_along(present_models)]

df_af5 <- df_af5 %>%
  mutate(
    shift_factor = factor(shift),
    shift_num = as.numeric(shift_factor),
    shift_num = case_when(
      shift == "Few-shot(10%)" ~ shift_num + 0.06,
      shift == "Few-shot(20%)" ~ shift_num + 0.06,
      TRUE ~ shift_num
    )
  )

p_af5 <- ggplot(df_af5, aes(x = shift_num, y = mean_auc, fill = model, pattern = model)) +
  geom_col_pattern(
    position = position_dodge(width = 0.8, preserve = "single"),
    width = 0.7,
    colour = "black",
    pattern_fill = "white",
    pattern_colour = NA,
    pattern_density = 0.4,
    pattern_spacing = 0.02,
    pattern_angle = 45
  ) +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.2,
    position = position_dodge(width = 0.8, preserve = "single")
  ) +
  geom_hline(yintercept = 0.5, color = "black", linewidth = 0.8) +
  theme_minimal(base_size = 14) +
  labs(title = "Atrial Fibrillation", y = "AUROC") +
  theme(
    axis.text.x  = element_text(face = "bold", size = 12),
    axis.text.y  = element_text(face = "bold", size = 12),
    axis.title.x = element_blank(),
    plot.title   = element_text(face = "bold", size = 18),
    legend.title = element_blank(),
    legend.text  = element_text(face = "bold", size = 10),
    legend.position = "top",
    legend.box = "horizontal",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  ) +
  scale_fill_manual(values = pal, drop = FALSE) +
  scale_pattern_manual(values = pattern_map, drop = FALSE) +
  coord_cartesian(ylim = c(0.5, 0.9), expand = FALSE) +
  scale_x_continuous(
    breaks = 1:length(levels(factor(df_af5$shift))),
    labels = levels(factor(df_af5$shift)),
    expand = c(0.1, 0)
  ) +
  guides(fill = guide_legend(nrow = 2))

p_af5

```


```{r}
df_hf5$label <- label_map[df_hf5$label]
df_hf5$model <- model_map[df_hf5$model]

present_models = intersect(order_models, unique(df_hf5$model))
df_hf5$model <- factor(df_hf5$model, levels = present_models)

pal <- c("#8C564B","#4C72B0","#66C2A5","#4C72B0","#66C2A5")[seq_along(present_models)]

df_hf5 <- df_hf5 %>%
  mutate(
    shift_factor = factor(shift),
    shift_num = as.numeric(shift_factor),
    shift_num = case_when(
      shift == "Few-shot(10%)" ~ shift_num + 0.06,
      shift == "Few-shot(20%)" ~ shift_num + 0.06,
      TRUE ~ shift_num
    )
  )

p_hf5 <- ggplot(df_hf5, aes(x = shift_num, y = mean_auc, fill = model, pattern = model)) +
  geom_col_pattern(
    position = position_dodge(width = 0.8, preserve = "single"),
    width = 0.7,
    colour = "black",
    pattern_fill = "white",
    pattern_colour = NA,
    pattern_density = 0.4,
    pattern_spacing = 0.02,
    pattern_angle = 45
  ) +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.2,
    position = position_dodge(width = 0.8, preserve = "single")
  ) +
  geom_hline(yintercept = 0.5, color = "black", linewidth = 0.8) +
  theme_minimal(base_size = 14) +
  labs(title = "Heart Failure", y = "AUROC") +
  theme(
    axis.text.x  = element_text(face = "bold", size = 12),
    axis.text.y  = element_text(face = "bold", size = 12),
    axis.title.x = element_blank(),
    plot.title   = element_text(face = "bold", size = 18),
    legend.title = element_blank(),
    legend.text  = element_text(face = "bold", size = 10),
    legend.position = "top",
    legend.box = "horizontal",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  ) +
  scale_fill_manual(values = pal, drop = FALSE) +
  scale_pattern_manual(values = pattern_map, drop = FALSE) +
  coord_cartesian(ylim = c(0.5, 0.9), expand = FALSE) +
  scale_x_continuous(
    breaks = 1:length(levels(factor(df_hf5$shift))),
    labels = levels(factor(df_hf5$shift)),
    expand = c(0.1, 0)
  ) +
  guides(fill = guide_legend(nrow = 2))

p_hf5

```


```{r}
s0  <- summary_auprc0  %>% mutate(shift = "Zero-shot")
s10 <- summary_auprc10 %>% mutate(shift = "Few-shot(10%)")
s20 <- summary_auprc20 %>% mutate(shift = "Few-shot(20%)")


df_af5 <- bind_rows(s0, s10, s20) %>%
  filter(label == "af5") %>%
  mutate(shift = factor(shift,
                        levels = c("Zero-shot", "Few-shot(10%)", "Few-shot(20%)")))


df_hf5 <- bind_rows(s0, s10, s20) %>%
  filter(label == "hf5") %>%
  mutate(shift = factor(shift,
                        levels = c("Zero-shot", "Few-shot(10%)", "Few-shot(20%)")))
```

```{r}
df_af5$label <- label_map[df_af5$label]
df_af5$model <- model_map[df_af5$model]

present_models = intersect(order_models, unique(df_af5$model))
df_af5$model <- factor(df_af5$model, levels = present_models)

pal <- c("#8C564B","#4C72B0","#66C2A5","#4C72B0","#66C2A5")[seq_along(present_models)]

df_af5 <- df_af5 %>%
  mutate(
    shift_factor = factor(shift),
    shift_num = as.numeric(shift_factor),
    shift_num = case_when(
      shift == "Few-shot(10%)" ~ shift_num + 0.06,
      shift == "Few-shot(20%)" ~ shift_num + 0.06,
      TRUE ~ shift_num
    )
  )

p_af5 <- ggplot(df_af5, aes(x = shift_num, y = mean_auprc, fill = model, pattern = model)) +
  geom_col_pattern(
    position = position_dodge(width = 0.8, preserve = "single"),
    width = 0.7,
    colour = "black",
    pattern_fill = "white",
    pattern_colour = NA,
    pattern_density = 0.4,
    pattern_spacing = 0.02,
    pattern_angle = 45
  ) +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.2,
    position = position_dodge(width = 0.8, preserve = "single")
  ) +
  geom_hline(yintercept = 0, color = "black", linewidth = 0.8) +
  theme_minimal(base_size = 14) +
  labs(title = "Atrial Fibrillation", y = "AUPRC") +
  theme(
    axis.text.x  = element_text(face = "bold", size = 12),
    axis.text.y  = element_text(face = "bold", size = 12),
    axis.title.x = element_blank(),
    plot.title   = element_text(face = "bold", size = 18),
    legend.title = element_blank(),
    legend.text  = element_text(face = "bold", size = 10),
    legend.position = "top",
    legend.box = "horizontal",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  ) +
  scale_fill_manual(values = pal, drop = FALSE) +
  scale_pattern_manual(values = pattern_map, drop = FALSE) +
  coord_cartesian(ylim = c(0, 0.3), expand = FALSE) +
  scale_x_continuous(
    breaks = 1:length(levels(factor(df_af5$shift))),
    labels = levels(factor(df_af5$shift)),
    expand = c(0.1, 0)
  ) +
  guides(fill = guide_legend(nrow = 2))

p_af5

```


```{r}
df_hf5$label <- label_map[df_hf5$label]
df_hf5$model <- model_map[df_hf5$model]

present_models = intersect(order_models, unique(df_hf5$model))
df_hf5$model <- factor(df_hf5$model, levels = present_models)
pal <- c("#8C564B","#4C72B0","#66C2A5","#4C72B0","#66C2A5")[seq_along(present_models)]
df_hf5 <- df_hf5 %>%
  mutate(
    shift_factor = factor(shift),
    shift_num = as.numeric(shift_factor),
    shift_num = case_when(
      shift == "Few-shot(10%)" ~ shift_num + 0.06,
      shift == "Few-shot(20%)" ~ shift_num + 0.06,
      TRUE ~ shift_num
    )
  )

p_hf5 <- ggplot(df_hf5, aes(x = shift_num, y = mean_auprc, fill = model, pattern = model)) +
  geom_col_pattern(
    position = position_dodge(width = 0.8, preserve = "single"),
    width = 0.7,
    colour = "black",
    pattern_fill = "white",
    pattern_colour = NA,
    pattern_density = 0.4,
    pattern_spacing = 0.02,
    pattern_angle = 45
  ) +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 0.2,
    position = position_dodge(width = 0.8, preserve = "single")
  ) +
  geom_hline(yintercept = 0, color = "black", linewidth = 0.8) +
  theme_minimal(base_size = 14) +
  labs(title = "Heart Failure", y = "AUPRC") +
  theme(
    axis.text.x  = element_text(face = "bold", size = 12),
    axis.text.y  = element_text(face = "bold", size = 12),
    axis.title.x = element_blank(),
    plot.title   = element_text(face = "bold", size = 18),
    legend.title = element_blank(),
    legend.text  = element_text(face = "bold", size = 10),
    legend.position = "top",
    legend.box = "horizontal",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  ) +
  scale_fill_manual(values = pal, drop = FALSE) +
  scale_pattern_manual(values = pattern_map, drop = FALSE) +
  coord_cartesian(ylim = c(0, 0.2), expand = FALSE) +
  scale_x_continuous(
    breaks = 1:length(levels(factor(df_hf5$shift))),
    labels = levels(factor(df_hf5$shift)),
    expand = c(0.1, 0)
  ) +
  guides(fill = guide_legend(nrow = 2))
p_hf5
```

