---
title: "Untitled"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Run UKBB and MESA imp first

```{r}
MESA_imp1
```


```{r}
library(dplyr)

make_prevent <- function(df) {
  df %>%
    mutate(
      sex_male = case_when(
        all(na.omit(gender) %in% c(0L, 1L)) ~ (gender == 1L),
        all(na.omit(gender) %in% c(1L, 2L)) ~ (gender == 1L),
        TRUE ~ NA
      ),
      age10 = (agec - 55) / 10,
      sbp_low  = (pmin(sbpc, 110) - 110) / 20,
      sbp_high = (pmax(sbpc, 110) - 130) / 20,
      bmi_low  = (pmin(bmic, 30) - 25) / 5,
      bmi_high = (pmax(bmic, 30) - 30) / 5,
      egfr_low  = (pmin(cepgfrc, 60) - 60) / (-15),
      egfr_high = (pmax(cepgfrc, 60) - 90) / (-15),
      diab   = (dm03c == 1),
      smoke  = (cigc == 1),
      htnmed = (htnmedc == 1),
      logodds_w =
        -4.310409 +
        0.8998235 * age10 +
        (-0.4559771) * sbp_low +
        0.3576505 * sbp_high +
        1.038346 * diab +
        0.583916 * smoke +
        (-0.0072294) * bmi_low +
        0.2997706 * bmi_high +
        0.7451638 * egfr_low +
        0.0557087 * egfr_high +
        0.3534442 * htnmed +
        (-0.0981511) * htnmed * sbp_high +
        (-0.0946663) * age10 * sbp_high +
        (-0.3581041) * age10 * diab +
        (-0.1159453) * age10 * smoke +
        (-0.0038780) * age10 * bmi_high +
        (-0.1884289) * age10 * egfr_low,
      logodds_m =
        -3.946391 +
        0.8972642 * age10 +
        (-0.6811466) * sbp_low +
        0.3634461 * sbp_high +
        0.923776 * diab +
        0.5023736 * smoke +
        (-0.0485841) * bmi_low +
        0.3726929 * bmi_high +
        0.6926917 * egfr_low +
        0.0251827 * egfr_high +
        0.2980922 * htnmed +
        (-0.0497731) * htnmed * sbp_high +
        (-0.1289201) * age10 * sbp_high +
        (-0.3040924) * age10 * diab +
        (-0.1401688) * age10 * smoke +
        0.0068126 * age10 * bmi_high +
        (-0.1797778) * age10 * egfr_low,
      logodds_prevent_hf = ifelse(sex_male, logodds_m, logodds_w),
      PREVENT_score = exp(logodds_prevent_hf) / (1 + exp(logodds_prevent_hf))
    ) %>%
    transmute(idno_visit, PREVENT_score)
}

MESA_PREVENT1 <- make_prevent(MESA_imp1)
MESA_PREVENT2 <- make_prevent(MESA_imp2)
MESA_PREVENT3 <- make_prevent(MESA_imp3)
MESA_PREVENT4 <- make_prevent(MESA_imp4)
```

```{r}
MESA_stage1 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/MESA/MESA_stage1_pred.csv")

make_MESA <- function(k) {
  MESA_stage1 %>%
    select(
      idno_visit,
      hf5_true,
      paste0("hf5_0_ECGstage1_downstream_pred", k),
      paste0("hf5_10_ECGstage1_downstream_pred", k),
      paste0("hf5_20_ECGstage1_downstream_pred", k)
    ) %>%
    rename(
      id     = idno_visit,
      hf5_0  = paste0("hf5_0_ECGstage1_downstream_pred", k),
      hf5_10 = paste0("hf5_10_ECGstage1_downstream_pred", k),
      hf5_20 = paste0("hf5_20_ECGstage1_downstream_pred", k),
      y_true = hf5_true
    )
}

MESA1 <- make_MESA(1)
MESA2 <- make_MESA(2)
MESA3 <- make_MESA(3)
MESA4 <- make_MESA(4)

```



```{r}
MESA1 <- merge(
  MESA1,
  MESA_PREVENT1,
  by.x = "id",
  by.y = "idno_visit",
  all.x = TRUE
)

MESA2 <- merge(
  MESA2,
  MESA_PREVENT2,
  by.x = "id",
  by.y = "idno_visit",
  all.x = TRUE
)

MESA3 <- merge(
  MESA3,
  MESA_PREVENT3,
  by.x = "id",
  by.y = "idno_visit",
  all.x = TRUE
)

MESA4 <- merge(
  MESA4,
  MESA_PREVENT4,
  by.x = "id",
  by.y = "idno_visit",
  all.x = TRUE
)
```


```{r}
UKBB_train <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/UKBB_train.csv")
colnames(UKBB_train)[1] <- "eid_visit"
UKBB_train$eid_visit <- sub("\\.mat$", "", UKBB_train$eid_visit)

UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT1 %>% 
      select(eid_visit, PREVENT_pred1 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT2 %>% 
      select(eid_visit, PREVENT_pred2 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT3 %>% 
      select(eid_visit, PREVENT_pred3 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT4 %>% 
      select(eid_visit, PREVENT_pred4 = PREVENT_score),
    by = "eid_visit"
  )
```



```{r}
UKBB_train1 <- UKBB_train %>%
  select(hf, hf1_pred, PREVENT_pred1) %>%
  na.omit()

UKBB_train2 <- UKBB_train %>%
  select(hf, hf2_pred, PREVENT_pred2) %>%
  na.omit()

UKBB_train3 <- UKBB_train %>%
  select(hf, hf3_pred, PREVENT_pred3) %>%
  na.omit()

UKBB_train4 <- UKBB_train %>%
  select(hf, hf4_pred, PREVENT_pred4) %>%
  na.omit()

```

```{r}
for (v in 1:4){
  fit <- glm(
      as.formula(paste0("hf ~ hf", v, "_pred + PREVENT_pred", v)),
      data = get(paste0("UKBB_train", v)),
      family = binomial(link = "logit")
    )
  for (ratio in c(0, 10, 20)) {

    df_eval <- get(paste0("MESA", v))[
      , c(paste0("hf5_", ratio), "PREVENT_score")
    ]

    mesa_name <- paste0("MESA", v)
    mesa_df <- get(mesa_name)

    newdata <- data.frame(
      setNames(list(mesa_df[[paste0("hf5_", ratio)]]), paste0("hf", v, "_pred")),
      setNames(list(mesa_df[["PREVENT_score"]]), paste0("PREVENT_pred", v))
    )

    mesa_df[[paste0("combined_pred", ratio)]] <- predict(fit, newdata = newdata, type = "response")
    assign(mesa_name, mesa_df)

  }
  
  out_dir <- paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/",
    "split", v, "/MESA/CHARGE_PREVENT"
  )
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

  df_out1<- mesa_df %>%
    dplyr::select(y_true, PREVENT_score) %>%
    dplyr::rename(
      y_true = y_true,
      y_pred = PREVENT_score
    ) %>%
    na.omit()

  write.csv(df_out1, file.path(out_dir, "test_hf5.csv"), row.names = FALSE)
  
  df_out2 <- mesa_df %>%
    dplyr::select(y_true, combined_pred0) %>%
    dplyr::rename(
      y_true = y_true,
      y_pred = combined_pred0
    ) %>%
    na.omit()

  write.csv(df_out2, file.path(out_dir, "test_hf5_cardiacfm0.csv"), row.names = FALSE)

  df_out3 <- mesa_df %>%
    dplyr::select(y_true, combined_pred10) %>%
    dplyr::rename(
      y_true = y_true,
      y_pred = combined_pred10
    ) %>%
    na.omit()

  write.csv(df_out3, file.path(out_dir, "test_hf5_cardiacfm10.csv"), row.names = FALSE)

  df_out4 <- mesa_df %>%
    dplyr::select(y_true, combined_pred20) %>%
    dplyr::rename(
      y_true = y_true,
      y_pred = combined_pred20
    ) %>%
    na.omit()

  write.csv(df_out4, file.path(out_dir, "test_hf5_cardiacfm20.csv"), row.names = FALSE)
  
}
```

```{r}
model_map <- c(
  hf5_0 = "CARDIAC-FM (0%)",
  hf5_10 = "CARDIAC-FM (10%)",
  hf5_20 = "CARDIAC-FM (20%)",
  PREVENT_score = "PREVENT(HF)",
  combined_pred0 = "CARDIAC-FM + PREVENT(HF) (0%)",
  combined_pred10 = "CARDIAC-FM + PREVENT(HF) (10%)",
  combined_pred20 = "CARDIAC-FM + PREVENT(HF) (20%)"
)

auc_summary <- list()

for (v in 1:4) {

  mesa_df <- get(paste0("MESA", v))

  for (col in names(model_map)) {

    df_tmp <- mesa_df %>%
      select(y_true, all_of(col)) %>%
      na.omit()

    auc_val <- auc(df_tmp$y_true, df_tmp[[col]])

    auc_summary[[length(auc_summary) + 1]] <- data.frame(
      MESA = paste0("CHS", v),
      model = model_map[[col]],
      auc = as.numeric(auc_val)
    )
  }
}

auc_summary_df <- bind_rows(auc_summary)
auc_mean_df <- auc_summary_df %>%
  group_by(model) %>%
  summarise(
    mean_auc = mean(auc),
    .groups = "drop"
  )
auc_mean_df
```

##### ECG-FM + CHARGE-AF

```{r}
MESA1 <- MESA1[,1:6]
MESA2 <- MESA1
MESA3 <- MESA1
MESA4 <- MESA1
idx  <- which(!is.na(MESA1$y_true))
```

```{r}
MESA1
```


```{r}
for (v in 1:4) {
  ecgfm0  <- read.csv(paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/split",
    v, "/MESA/ECGFM_downstream/test_hf5_long_full_0.csv"
  ))
  ecgfm10 <- read.csv(paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/split",
    v, "/MESA/ECGFM_downstream/test_hf5_long_full_10.csv"
  ))
  ecgfm20 <- read.csv(paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/split",
    v, "/MESA/ECGFM_downstream/test_hf5_long_full_20.csv"
  ))
  mesa_name <- paste0("MESA", v)
  mesa_df   <- get(mesa_name)

  idx <- which(!is.na(mesa_df$hf5_0))

  stopifnot(
    length(idx) == nrow(ecgfm0),
    length(idx) == nrow(ecgfm10),
    length(idx) == nrow(ecgfm20)
  )

  mesa_df$hf5_0[idx]  <- ecgfm0$y_pred
  mesa_df$hf5_10[idx] <- ecgfm10$y_pred
  mesa_df$hf5_20[idx] <- ecgfm20$y_pred

  assign(mesa_name, mesa_df)
}
```

```{r}
MESA1
```


```{r}
UKBB_train <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/UKBB_train_ecgfm.csv")
colnames(UKBB_train)[1] <- "eid_visit"
UKBB_train$eid_visit <- sub("\\.mat$", "", UKBB_train$eid_visit)

UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT1 %>% 
      select(eid_visit, PREVENT_pred1 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT2 %>% 
      select(eid_visit, PREVENT_pred2 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT3 %>% 
      select(eid_visit, PREVENT_pred3 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT4 %>% 
      select(eid_visit, PREVENT_pred4 = PREVENT_score),
    by = "eid_visit"
  )
```



```{r}
UKBB_train1 <- UKBB_train %>%
  select(hf, hf1_pred, PREVENT_pred1) %>%
  na.omit()

UKBB_train2 <- UKBB_train %>%
  select(hf, hf2_pred, PREVENT_pred2) %>%
  na.omit()

UKBB_train3 <- UKBB_train %>%
  select(hf, hf3_pred, PREVENT_pred3) %>%
  na.omit()

UKBB_train4 <- UKBB_train %>%
  select(hf, hf4_pred, PREVENT_pred4) %>%
  na.omit()

```


```{r}
for (v in 1:4){
  fit <- glm(
      as.formula(paste0("hf ~ hf", v, "_pred + PREVENT_pred", v)),
      data = get(paste0("UKBB_train", v)),
      family = binomial(link = "logit")
    )
  for (ratio in c(0, 10, 20)) {

    df_eval <- get(paste0("MESA", v))[
      , c(paste0("hf5_", ratio), "PREVENT_score")
    ]

    mesa_name <- paste0("MESA", v)
    mesa_df <- get(mesa_name)

    newdata <- data.frame(
      setNames(list(mesa_df[[paste0("hf5_", ratio)]]), paste0("hf", v, "_pred")),
      setNames(list(mesa_df[["PREVENT_score"]]), paste0("PREVENT_pred", v))
    )

    mesa_df[[paste0("combined_pred", ratio)]] <- predict(fit, newdata = newdata, type = "response")
    assign(mesa_name, mesa_df)

  }
  
  out_dir <- paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/",
    "split", v, "/MESA/CHARGE_PREVENT"
  )
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  
  df_out2 <- mesa_df %>%
    dplyr::select(y_true, combined_pred0) %>%
    dplyr::rename(
      y_true = y_true,
      y_pred = combined_pred0
    ) %>%
    na.omit()

  write.csv(df_out2, file.path(out_dir, "test_hf5_ecgfm0.csv"), row.names = FALSE)

  df_out3 <- mesa_df %>%
    dplyr::select(y_true, combined_pred10) %>%
    dplyr::rename(
      y_true = y_true,
      y_pred = combined_pred10
    ) %>%
    na.omit()

  write.csv(df_out3, file.path(out_dir, "test_hf5_ecgfm10.csv"), row.names = FALSE)

  df_out4 <- mesa_df %>%
    dplyr::select(y_true, combined_pred20) %>%
    dplyr::rename(
      y_true = y_true,
      y_pred = combined_pred20
    ) %>%
    na.omit()

  write.csv(df_out4, file.path(out_dir, "test_hf5_ecgfm20.csv"), row.names = FALSE)
}
```

```{r}
model_map <- c(
  hf5_0 = "ECG-FM (0%)",
  hf5_10 = "ECG-FM (10%)",
  hf5_20 = "ECG-FM (20%)",
  PREVENT_score = "PREVENT(HF)",
  combined_pred0 = "ECG-FM + PREVENT(HF) (0%)",
  combined_pred10 = "ECG-FM + PREVENT(HF) (10%)",
  combined_pred20 = "ECG-FM + PREVENT(HF) (20%)"
)

auc_summary <- list()

for (v in 1:4) {

  mesa_df <- get(paste0("MESA", v))

  for (col in names(model_map)) {

    df_tmp <- mesa_df %>%
      select(y_true, all_of(col)) %>%
      na.omit()

    auc_val <- auc(df_tmp$y_true, df_tmp[[col]])

    auc_summary[[length(auc_summary) + 1]] <- data.frame(
      MESA = paste0("MESA", v),
      model = model_map[[col]],
      auc = as.numeric(auc_val)
    )
  }
}

auc_summary_df <- bind_rows(auc_summary)
auc_mean_df <- auc_summary_df %>%
  group_by(model) %>%
  summarise(
    mean_auc = mean(auc),
    .groups = "drop"
  )
auc_mean_df
```






