---
title: "PREVENT"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
UKBB <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/charge_prevent_UKBB.csv")
```

```{r}
library(mice)

set.seed(123)
id <- UKBB$eid_visit

dat <- UKBB
dat$eid_visit <- NULL

imp <- mice(
  dat,
  m = 4,
  maxit = 20,
  seed = 123,
  printFlag = TRUE
)

UKBB_imp_list <- lapply(1:4, function(i) {
  out <- complete(imp, action = i)
  out$eid_visit <- id
  out <- out[, c("eid_visit", setdiff(colnames(out), "eid_visit"))]
  out
})

UKBB_imp1 <- UKBB_imp_list[[1]]
UKBB_imp2 <- UKBB_imp_list[[2]]
UKBB_imp3 <- UKBB_imp_list[[3]]
UKBB_imp4 <- UKBB_imp_list[[4]]
```


```{r}
library(dplyr)

make_prevent <- function(df) {
  df %>%
    mutate(
      sex_male = case_when(
        all(na.omit(sex) %in% c(0L, 1L)) ~ (sex == 1L),
        all(na.omit(sex) %in% c(1L, 2L)) ~ (sex == 1L),
        TRUE ~ NA
      ),
      age10 = (agecmr - 55) / 10,
      sbp_low  = (pmin(sbp, 110) - 110) / 20,
      sbp_high = (pmax(sbp, 110) - 130) / 20,
      bmi_low  = (pmin(bmi, 30) - 25) / 5,
      bmi_high = (pmax(bmi, 30) - 30) / 5,
      egfr_low  = (pmin(egfrcr, 60) - 60) / (-15),
      egfr_high = (pmax(egfrcr, 60) - 90) / (-15),
      diab   = (dm == 1),
      smoke  = (cursmoke == 1),
      htnmed = (htnmed == 1),
      logodds_w =
        -4.310409 +
        0.8998235 * age10 +
        (-0.4559771) * sbp_low +
        0.3576505 * sbp_high +
        1.038346 * diab +
        0.583916 * smoke +
        (-0.0072294) * bmi_low +
        0.2997706 * bmi_high +
        0.7451638 * egfr_low +
        0.0557087 * egfr_high +
        0.3534442 * htnmed +
        (-0.0981511) * htnmed * sbp_high +
        (-0.0946663) * age10 * sbp_high +
        (-0.3581041) * age10 * diab +
        (-0.1159453) * age10 * smoke +
        (-0.0038780) * age10 * bmi_high +
        (-0.1884289) * age10 * egfr_low,
      logodds_m =
        -3.946391 +
        0.8972642 * age10 +
        (-0.6811466) * sbp_low +
        0.3634461 * sbp_high +
        0.923776 * diab +
        0.5023736 * smoke +
        (-0.0485841) * bmi_low +
        0.3726929 * bmi_high +
        0.6926917 * egfr_low +
        0.0251827 * egfr_high +
        0.2980922 * htnmed +
        (-0.0497731) * htnmed * sbp_high +
        (-0.1289201) * age10 * sbp_high +
        (-0.3040924) * age10 * diab +
        (-0.1401688) * age10 * smoke +
        0.0068126 * age10 * bmi_high +
        (-0.1797778) * age10 * egfr_low,
      logodds_prevent_hf = ifelse(sex_male, logodds_m, logodds_w),
      PREVENT_score = exp(logodds_prevent_hf) / (1 + exp(logodds_prevent_hf))
    ) %>%
    transmute(eid_visit, PREVENT_score)
}

UKBB_PREVENT1 <- make_prevent(UKBB_imp1)
UKBB_PREVENT2 <- make_prevent(UKBB_imp2)
UKBB_PREVENT3 <- make_prevent(UKBB_imp3)
UKBB_PREVENT4 <- make_prevent(UKBB_imp4)

```


### CARDIAC-FM + PREVENT(HF)


```{r}
test1 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGstage1_UKBB_split1.csv")
test2 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGstage1_UKBB_split2.csv")
test3 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGstage1_UKBB_split3.csv")
test4 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGstage1_UKBB_split4.csv")
```


```{r}
test1 <- test1 %>%
  left_join(
    UKBB_PREVENT1 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test2 <- test2%>%
  left_join(
    UKBB_PREVENT2 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test3 <- test3 %>%
  left_join(
    UKBB_PREVENT3 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test4 <- test4 %>%
  left_join(
    UKBB_PREVENT4 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )
```

```{r}
ecgmri <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_HR/ecgmri.csv")
test1 <- test1 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test2 <- test2 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test3 <- test3 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test4 <- test4 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
```

```{r}
UKBB_train <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/UKBB_train.csv")
colnames(UKBB_train)[1] <- "eid_visit"
UKBB_train$eid_visit <- sub("\\.mat$", "", UKBB_train$eid_visit)

UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT1 %>% 
      select(eid_visit, PREVENT_pred1 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT2 %>% 
      select(eid_visit, PREVENT_pred2 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT3 %>% 
      select(eid_visit, PREVENT_pred3 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT4 %>% 
      select(eid_visit, PREVENT_pred4 = PREVENT_score),
    by = "eid_visit"
  )
```



```{r}
UKBB_train1 <- UKBB_train %>%
  select(hf, hf1_pred, PREVENT_pred1) %>%
  na.omit()

UKBB_train2 <- UKBB_train %>%
  select(hf, hf2_pred, PREVENT_pred2) %>%
  na.omit()

UKBB_train3 <- UKBB_train %>%
  select(hf, hf3_pred, PREVENT_pred3) %>%
  na.omit()

UKBB_train4 <- UKBB_train %>%
  select(hf, hf4_pred, PREVENT_pred4) %>%
  na.omit()

```

```{r}
library(dplyr)
library(pROC)

results <- list()

for (v in 1:4) {

  df_eval <- get(paste0("test", v)) %>%
    select(eid_visit, hf5, hf5_pred, PREVENT_score) %>%
    rename(
      hf = hf5,
      !!paste0("hf", v, "_pred") := hf5_pred,
      !!paste0("PREVENT_pred", v) := PREVENT_score
    ) %>%
    na.omit()

  fit <- glm(
    as.formula(paste0("hf ~ hf", v, "_pred + PREVENT_pred", v)),
    data = get(paste0("UKBB_train", v)),
    family = binomial(link = "logit")
  )

  df_eval$model_pred <- predict(fit, newdata = df_eval, type = "response")
  
  out_dir <- paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/",
    "split", v, "/UKBB/CHARGE_PREVENT"
  )
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

  df_out1 <- df_eval %>%
    dplyr::select(hf, !!paste0("hf", v, "_pred")) %>%
    dplyr::rename(
      y_true = hf,
      y_pred = !!paste0("hf", v, "_pred")
    )

  write.csv(df_out1, file.path(out_dir, "test_hf5.csv"), row.names = FALSE)

  df_out2 <- df_eval %>%
    dplyr::select(hf, model_pred) %>%
    dplyr::rename(
      y_true = hf,
      y_pred = model_pred
    )

  write.csv(df_out2, file.path(out_dir, "test_hf5_cardiacfm.csv"), row.names = FALSE)

  out_dir2 <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease"
  write.csv(df_eval, file.path(out_dir2, paste0("cardiacfm_prevent_split", v,".csv")), row.names = FALSE)
  
  results[[v]] <- data.frame(
    version = v,
    auc_model  = as.numeric(auc(df_eval$hf, df_eval$model_pred)),
    auc_af     = as.numeric(auc(df_eval$hf, df_eval[[paste0("hf", v, "_pred")]])),
    auc_charge = as.numeric(auc(df_eval$hf, df_eval[[paste0("PREVENT_pred", v)]])
    )
  )
}

auc_summary <- bind_rows(results)
auc_summary
```

```{r}
data.frame(
  Model = c(
    "CARDIAC-FM(ECG) + CHARGE-AF",
    "CARDIAC-FM(ECG)",
    "CHARGE-AF"
  ),
  AUC = colMeans(auc_summary[, c("auc_model", "auc_af", "auc_charge")])
)
```


##### ECG-FM + CHARGE-AF


```{r}
test1 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGFM_UKBB_split1.csv")
test2 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGFM_UKBB_split2.csv")
test3 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGFM_UKBB_split3.csv")
test4 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGFM_UKBB_split4.csv")
```


```{r}
test1 <- test1 %>%
  left_join(
    UKBB_PREVENT1 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test2 <- test2%>%
  left_join(
    UKBB_PREVENT2 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test3 <- test3 %>%
  left_join(
    UKBB_PREVENT3 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test4 <- test4 %>%
  left_join(
    UKBB_PREVENT4 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )
```

```{r}
ecgmri <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_HR/ecgmri.csv")
test1 <- test1 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test2 <- test2 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test3 <- test3 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test4 <- test4 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
```

```{r}
UKBB_train <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/UKBB_train_ecgfm.csv")
colnames(UKBB_train)[1] <- "eid_visit"
UKBB_train$eid_visit <- sub("\\.mat$", "", UKBB_train$eid_visit)

UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT1 %>% 
      select(eid_visit, PREVENT_pred1 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT2 %>% 
      select(eid_visit, PREVENT_pred2 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT3 %>% 
      select(eid_visit, PREVENT_pred3 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT4 %>% 
      select(eid_visit, PREVENT_pred4 = PREVENT_score),
    by = "eid_visit"
  )
```



```{r}
UKBB_train1 <- UKBB_train %>%
  select(hf, hf1_pred, PREVENT_pred1) %>%
  na.omit()

UKBB_train2 <- UKBB_train %>%
  select(hf, hf2_pred, PREVENT_pred2) %>%
  na.omit()

UKBB_train3 <- UKBB_train %>%
  select(hf, hf3_pred, PREVENT_pred3) %>%
  na.omit()

UKBB_train4 <- UKBB_train %>%
  select(hf, hf4_pred, PREVENT_pred4) %>%
  na.omit()

```

```{r}
library(dplyr)
library(pROC)

results <- list()

for (v in 1:4) {

  df_eval <- get(paste0("test", v)) %>%
    select(eid_visit, hf5, hf5_pred, PREVENT_score) %>%
    rename(
      hf = hf5,
      !!paste0("hf", v, "_pred") := hf5_pred,
      !!paste0("PREVENT_pred", v) := PREVENT_score
    ) %>%
    na.omit()

  fit <- glm(
    as.formula(paste0("hf ~ hf", v, "_pred + PREVENT_pred", v)),
    data = get(paste0("UKBB_train", v)),
    family = binomial(link = "logit")
  )

  df_eval$model_pred <- predict(fit, newdata = df_eval, type = "response")

  out_dir <- paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/",
    "split", v, "/UKBB/CHARGE_PREVENT"
  )
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

  df_out2 <- df_eval %>%
    dplyr::select(hf, model_pred) %>%
    dplyr::rename(
      y_true = hf,
      y_pred = model_pred
    )

  write.csv(df_out2, file.path(out_dir, "test_hf5_ecgfm.csv"), row.names = FALSE)
  
  out_dir2 <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease"
  write.csv(df_eval, file.path(out_dir2, paste0("ecgfm_prevent_split", v,".csv")), row.names = FALSE)

  results[[v]] <- data.frame(
    version = v,
    auc_model  = as.numeric(auc(df_eval$hf, df_eval$model_pred)),
    auc_af     = as.numeric(auc(df_eval$hf, df_eval[[paste0("hf", v, "_pred")]])),
    auc_charge = as.numeric(auc(df_eval$hf, df_eval[[paste0("PREVENT_pred", v)]])
    )
  )
}

auc_summary <- bind_rows(results)
auc_summary
```

```{r}
data.frame(
  Model = c(
    "ECG-FM(ECG) + PREVENT(HF)",
    "ECG-FM(ECG)",
    "PREVENT(HF)"
  ),
  AUC = colMeans(auc_summary[, c("auc_model", "auc_af", "auc_charge")])
)
```


##### CARDIAC-FM(ECG+MRI) + CHARGE-AF

```{r}
test1 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGMRIstage1_UKBB_split1.csv")
test2 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGMRIstage1_UKBB_split2.csv")
test3 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGMRIstage1_UKBB_split3.csv")
test4 <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease/ECGMRIstage1_UKBB_split4.csv")
```


```{r}
test1 <- test1 %>%
  left_join(
    UKBB_PREVENT1 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test2 <- test2%>%
  left_join(
    UKBB_PREVENT2 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test3 <- test3 %>%
  left_join(
    UKBB_PREVENT3 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )

test4 <- test4 %>%
  left_join(
    UKBB_PREVENT4 %>% 
      select(eid_visit, PREVENT_score),
    by = "eid_visit"
  )
```

```{r}
ecgmri <- read.csv("/Users/fuminli/Desktop/ECG_MRI/csv_HR/ecgmri.csv")
test1 <- test1 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test2 <- test2 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test3 <- test3 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
test4 <- test4 %>% dplyr::filter(eid_visit %in% ecgmri$eid_visit)
```

```{r}
UKBB_train <- read.csv("/Users/fuminli/Desktop/ECG_MRI/CHARGE-PREVENT/UKBB_train_ecgmri.csv")
colnames(UKBB_train)[1] <- "eid_visit"
UKBB_train$eid_visit <- sub("\\.mat$", "", UKBB_train$eid_visit)

UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT1 %>% 
      select(eid_visit, PREVENT_pred1 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT2 %>% 
      select(eid_visit, PREVENT_pred2 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT3 %>% 
      select(eid_visit, PREVENT_pred3 = PREVENT_score),
    by = "eid_visit"
  )
UKBB_train <- UKBB_train %>%
  left_join(
    UKBB_PREVENT4 %>% 
      select(eid_visit, PREVENT_pred4 = PREVENT_score),
    by = "eid_visit"
  )
```



```{r}
UKBB_train1 <- UKBB_train %>%
  select(hf, hf1_pred, PREVENT_pred1) %>%
  na.omit()

UKBB_train2 <- UKBB_train %>%
  select(hf, hf2_pred, PREVENT_pred2) %>%
  na.omit()

UKBB_train3 <- UKBB_train %>%
  select(hf, hf3_pred, PREVENT_pred3) %>%
  na.omit()

UKBB_train4 <- UKBB_train %>%
  select(hf, hf4_pred, PREVENT_pred4) %>%
  na.omit()

```

```{r}
library(dplyr)
library(pROC)

results <- list()

for (v in 1:4) {

  df_eval <- get(paste0("test", v)) %>%
    select(eid_visit, hf5, hf5_pred, PREVENT_score) %>%
    rename(
      hf = hf5,
      !!paste0("hf", v, "_pred") := hf5_pred,
      !!paste0("PREVENT_pred", v) := PREVENT_score
    ) %>%
    na.omit()

  fit <- glm(
    as.formula(paste0("hf ~ hf", v, "_pred + PREVENT_pred", v)),
    data = get(paste0("UKBB_train", v)),
    family = binomial(link = "logit")
  )

  df_eval$model_pred <- predict(fit, newdata = df_eval, type = "response")

  out_dir <- paste0(
    "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp/",
    "split", v, "/UKBB/CHARGE_PREVENT"
  )
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  
  df_out2 <- df_eval %>%
    dplyr::select(hf, model_pred) %>%
    dplyr::rename(
      y_true = hf,
      y_pred = model_pred
    )

  write.csv(df_out2, file.path(out_dir, "test_hf5_cardiacfm_ecgmri.csv"), row.names = FALSE)
  
  out_dir2 <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_id_disease"
  write.csv(df_eval, file.path(out_dir2, paste0("cardiacfm_ecgmri_prevent_split", v,".csv")), row.names = FALSE)

  results[[v]] <- data.frame(
    version = v,
    auc_model  = as.numeric(auc(df_eval$hf, df_eval$model_pred)),
    auc_af     = as.numeric(auc(df_eval$hf, df_eval[[paste0("hf", v, "_pred")]])),
    auc_charge = as.numeric(auc(df_eval$hf, df_eval[[paste0("PREVENT_pred", v)]])
    )
  )
}

auc_summary <- bind_rows(results)
auc_summary
```


```{r}
data.frame(
  Model = c(
    "CARDIAC-FM + PREVENT(HF)",
    "CARDIAC-FM",
    "PREVENT(HF)"
  ),
  AUC = colMeans(auc_summary[, c("auc_model", "auc_af", "auc_charge")])
)
```


```{r}
data.frame(
  Model = c(
    "CARDIAC-FM(ECG+MRI) + PREVENT(HF)",
    "CARDIAC-FM(ECG+MRI)",
    "PREVENT(HF)"
  ),
  AUC = colMeans(auc_summary[, c("auc_model", "auc_af", "auc_charge")])
)
```

