---
title: "UKBB_R2_Corr"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

########## Continuous variable

# For those without pre AF and HF


```{r}
library(dplyr)
library(ggplot2)
library(cowplot)

true <- read.csv("/Users/fuminli/Desktop/ECG_MRI/UKBB_cmr_true_test.csv")
base_dir <- "/Users/fuminli/Desktop/ECG_MRI/csv_train_valid_test_individual_temp"
splits <- 1:4
labels <- c("LAVmin", "LAVmax", "LAEF", "LVEF", "LVEDV", "LVESV", "LVM")

all_results <- list()

for (sp in splits) {
  for (label in labels) {

    label_lc <- tolower(label)

    df_true <- true[, c(label_lc, "healthy")]
    df_true <- df_true[!is.na(df_true[[label_lc]]), ]
    rownames(df_true) <- NULL
    idx_healthy <- which(df_true$healthy == 1)

    file_path <- file.path(
      base_dir, paste0("split", sp), "UKBB",
      paste0("ECGstage1_downstream/test_", label_lc, "_long_full.csv")
    )
    if (!file.exists(file_path)) next

    df <- read.csv(file_path)
    df <- df[!is.na(df$y_true), ]
    rownames(df) <- NULL

    df_sub <- df[idx_healthy, ]

    corr <- cor(df_sub$y_true, df_sub$y_pred)
    variance <- var(df_sub$y_true)
    mse <- mean((df_sub$y_true - df_sub$y_pred)^2)
    r2 <- 1 - (mse / variance)

    all_results[[length(all_results) + 1]] <- data.frame(
      split = sp,
      label = label,
      corr = corr,
      r2 = r2
    )
  }
}

all_results <- bind_rows(all_results)

all_results$label <- factor(
  all_results$label,
  levels = c("LAVmin", "LAVmax", "LAEF", "LVEF", "LVEDV", "LVESV", "LVM")
)

```

```{r}
summary_results <- all_results %>%
  group_by(label) %>%
  summarise(
    mean_corr  = mean(corr),
    sd_corr    = sd(corr),
    lower_corr = mean_corr - 1.96 * sd_corr / sqrt(n()),
    upper_corr = mean_corr + 1.96 * sd_corr / sqrt(n()),
    
    mean_r2  = mean(r2),
    sd_r2    = sd(r2),
    lower_r2 = mean_r2 - 1.96 * sd_r2 / sqrt(n()),
    upper_r2 = mean_r2 + 1.96 * sd_r2 / sqrt(n())
  )

```

```{r}
p_corr <- ggplot(summary_results, aes(x = label, y = mean_corr)) +
  geom_col(fill = "#2E5A87", width = 0.7) +
  geom_errorbar(aes(ymin = lower_corr, ymax = upper_corr), width = 0.2) +
  theme_minimal(base_size = 15) +
  ylim(0, 1) +
  labs(x = "", y = "Pearson Corr") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, face = "bold"),
    plot.title = element_text(hjust = 0.5)
  )

p_r2 <- ggplot(summary_results, aes(x = label, y = mean_r2)) +
  geom_col(fill = "#2E5A87", width = 0.7) +
  geom_errorbar(aes(ymin = lower_r2, ymax = upper_r2), width = 0.2) +
  theme_minimal(base_size = 15) +
  labs(
    x = "", 
    y = expression(R^2)      
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, face = "bold"),
    plot.title = element_text(hjust = 0.5)
  )

library(patchwork)

combined_plot <- p_corr + p_r2 +
  plot_annotation(title = "CMR Features", 
                  theme = theme(plot.title = element_text(hjust = 0.2, size = 18, face = "bold"))) +
  plot_layout(ncol = 2) 

print(combined_plot)
```

```{r}
write.csv(summary_results, "/Users/fuminli/Desktop/ECG_MRI/result_table/UKBB_r2_corr_healthy.csv", row.names = FALSE)
```

